// <auto-generated />
namespace Uptail.Commerce.RetailProxy.Extension
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using Microsoft.Dynamics.Commerce.RetailProxy;
    using Microsoft.Dynamics.Commerce.RetailProxy.Adapters;
    using Microsoft.OData.Client;
    
    /// <summary>
    /// MagicBox entity class.
    /// </summary>
    [Microsoft.OData.Client.Key("BoxNumber")]
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public class MagicBox : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="MagicBox" /> class.
        /// 
        public MagicBox()
        {
            
        }
      
        /// <summary>
        /// Gets or sets the BoxNumber.
        /// </summary>
        public string BoxNumber
        {
            get
            {
                return this._boxNumber;
            }
        
            set
            {
                this._boxNumber = value;
                this.OnPropertyChanged("BoxNumber");
            }
        }
      
        private string _boxNumber;
      
        /// <summary>
        /// Gets or sets the BoxName.
        /// </summary>
        public string BoxName
        {
            get
            {
                return this._boxName;
            }
        
            set
            {
                this._boxName = value;
                this.OnPropertyChanged("BoxName");
            }
        }
      
        private string _boxName;
      
        /// <summary>
        /// Gets or sets the BoxPurchased.
        /// </summary>
        public bool? BoxPurchased
        {
            get
            {
                return this._boxPurchased;
            }
        
            set
            {
                this._boxPurchased = value;
                this.OnPropertyChanged("BoxPurchased");
            }
        }
      
        private bool? _boxPurchased;
      
    }
    
    /// <summary>
    /// CustomerHistory entity class.
    /// </summary>
    [Microsoft.OData.Client.Key("CustometId")]
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public class CustomerHistory : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="CustomerHistory" /> class.
        /// 
        public CustomerHistory()
        {
            
        }
      
        /// <summary>
        /// Gets or sets the CustometId.
        /// </summary>
        public string CustometId
        {
            get
            {
                return this._custometId;
            }
        
            set
            {
                this._custometId = value;
                this.OnPropertyChanged("CustometId");
            }
        }
      
        private string _custometId;
      
        /// <summary>
        /// Gets or sets the StoreId.
        /// </summary>
        public string StoreId
        {
            get
            {
                return this._storeId;
            }
        
            set
            {
                this._storeId = value;
                this.OnPropertyChanged("StoreId");
            }
        }
      
        private string _storeId;
      
        /// <summary>
        /// Gets or sets the TransactionId.
        /// </summary>
        public string TransactionId
        {
            get
            {
                return this._transactionId;
            }
        
            set
            {
                this._transactionId = value;
                this.OnPropertyChanged("TransactionId");
            }
        }
      
        private string _transactionId;
      
        /// <summary>
        /// Gets or sets the SalesDateTime.
        /// </summary>
        public DateTimeOffset? SalesDateTime
        {
            get
            {
                return this._salesDateTime;
            }
        
            set
            {
                this._salesDateTime = value;
                this.OnPropertyChanged("SalesDateTime");
            }
        }
      
        private DateTimeOffset? _salesDateTime;
      
        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        public string Description
        {
            get
            {
                return this._description;
            }
        
            set
            {
                this._description = value;
                this.OnPropertyChanged("Description");
            }
        }
      
        private string _description;
      
        /// <summary>
        /// Gets or sets the ItemNumber.
        /// </summary>
        public string ItemNumber
        {
            get
            {
                return this._itemNumber;
            }
        
            set
            {
                this._itemNumber = value;
                this.OnPropertyChanged("ItemNumber");
            }
        }
      
        private string _itemNumber;
      
        /// <summary>
        /// Gets or sets the Quantity.
        /// </summary>
        public decimal? Quantity
        {
            get
            {
                return this._quantity;
            }
        
            set
            {
                this._quantity = value;
                this.OnPropertyChanged("Quantity");
            }
        }
      
        private decimal? _quantity;
      
        /// <summary>
        /// Gets or sets the Price.
        /// </summary>
        public decimal? Price
        {
            get
            {
                return this._price;
            }
        
            set
            {
                this._price = value;
                this.OnPropertyChanged("Price");
            }
        }
      
        private decimal? _price;
      
        /// <summary>
        /// Gets or sets the Amount.
        /// </summary>
        public decimal? Amount
        {
            get
            {
                return this._amount;
            }
        
            set
            {
                this._amount = value;
                this.OnPropertyChanged("Amount");
            }
        }
      
        private decimal? _amount;
      
        /// <summary>
        /// Gets or sets the Currency.
        /// </summary>
        public string Currency
        {
            get
            {
                return this._currency;
            }
        
            set
            {
                this._currency = value;
                this.OnPropertyChanged("Currency");
            }
        }
      
        private string _currency;
      
    }
    
    /// <summary>
    /// ItemBarCodes entity class.
    /// </summary>
    [Microsoft.OData.Client.Key("Barcode")]
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public class ItemBarCodes : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="ItemBarCodes" /> class.
        /// 
        public ItemBarCodes()
        {
            
            this._extensionProperties.CollectionChanged += ExtensionProperties_OnCollectionChanged;
        }
      
        /// <summary>
        /// Gets or sets the Barcode.
        /// </summary>
        public string Barcode
        {
            get
            {
                return this._barcode;
            }
        
            set
            {
                this._barcode = value;
                this.OnPropertyChanged("Barcode");
            }
        }
      
        private string _barcode;
      
        /// <summary>
        /// Gets or sets the ItemId.
        /// </summary>
        public string ItemId
        {
            get
            {
                return this._itemId;
            }
        
            set
            {
                this._itemId = value;
                this.OnPropertyChanged("ItemId");
            }
        }
      
        private string _itemId;
      
        /// <summary>
        /// Gets or sets the RetailVariantId.
        /// </summary>
        public string RetailVariantId
        {
            get
            {
                return this._retailVariantId;
            }
        
            set
            {
                this._retailVariantId = value;
                this.OnPropertyChanged("RetailVariantId");
            }
        }
      
        private string _retailVariantId;
      
        /// <summary>
        /// Gets or sets the ExtensionProperties.
        /// </summary>
        public ObservableCollection<CommerceProperty> ExtensionProperties
        {
            get
            {
                return this._extensionProperties;
            }
        
            set
            {
                this._extensionProperties = value;
                this.OnPropertyChanged("ExtensionProperties");
            }
        }
      
        private void ExtensionProperties_OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnPropertyChanged("ExtensionProperties");  
        }
    
        private ObservableCollection<CommerceProperty> _extensionProperties = new ObservableCollection<CommerceProperty>();
      
    }
    
    /// <summary>
    /// LegacySalesTransaction entity class.
    /// </summary>
    
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public class LegacySalesTransaction : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="LegacySalesTransaction" /> class.
        /// 
        public LegacySalesTransaction()
        {
            
        }
      
        /// <summary>
        /// Gets or sets the StoreId.
        /// </summary>
        public string StoreId
        {
            get
            {
                return this._storeId;
            }
        
            set
            {
                this._storeId = value;
                this.OnPropertyChanged("StoreId");
            }
        }
      
        private string _storeId;
      
        /// <summary>
        /// Gets or sets the TransactionId.
        /// </summary>
        public string TransactionId
        {
            get
            {
                return this._transactionId;
            }
        
            set
            {
                this._transactionId = value;
                this.OnPropertyChanged("TransactionId");
            }
        }
      
        private string _transactionId;
      
        /// <summary>
        /// Gets or sets the SalesDateTime.
        /// </summary>
        public DateTimeOffset? SalesDateTime
        {
            get
            {
                return this._salesDateTime;
            }
        
            set
            {
                this._salesDateTime = value;
                this.OnPropertyChanged("SalesDateTime");
            }
        }
      
        private DateTimeOffset? _salesDateTime;
      
        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        public string Description
        {
            get
            {
                return this._description;
            }
        
            set
            {
                this._description = value;
                this.OnPropertyChanged("Description");
            }
        }
      
        private string _description;
      
        /// <summary>
        /// Gets or sets the ItemNumber.
        /// </summary>
        public string ItemNumber
        {
            get
            {
                return this._itemNumber;
            }
        
            set
            {
                this._itemNumber = value;
                this.OnPropertyChanged("ItemNumber");
            }
        }
      
        private string _itemNumber;
      
        /// <summary>
        /// Gets or sets the Quantity.
        /// </summary>
        public decimal? Quantity
        {
            get
            {
                return this._quantity;
            }
        
            set
            {
                this._quantity = value;
                this.OnPropertyChanged("Quantity");
            }
        }
      
        private decimal? _quantity;
      
        /// <summary>
        /// Gets or sets the Price.
        /// </summary>
        public decimal? Price
        {
            get
            {
                return this._price;
            }
        
            set
            {
                this._price = value;
                this.OnPropertyChanged("Price");
            }
        }
      
        private decimal? _price;
      
        /// <summary>
        /// Gets or sets the Amount.
        /// </summary>
        public decimal? Amount
        {
            get
            {
                return this._amount;
            }
        
            set
            {
                this._amount = value;
                this.OnPropertyChanged("Amount");
            }
        }
      
        private decimal? _amount;
      
        /// <summary>
        /// Gets or sets the Currency.
        /// </summary>
        public string Currency
        {
            get
            {
                return this._currency;
            }
        
            set
            {
                this._currency = value;
                this.OnPropertyChanged("Currency");
            }
        }
      
        private string _currency;
      
    }
    
}
  