// <auto-generated />
namespace Uptail.Commerce.RetailProxy.Extension.Adapters
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.IO;
    using System.Threading.Tasks;

    
    /// <summary>
    /// Interface for Store Operations Manager.
    /// </summary>
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public interface IStoreOperationsManager : Microsoft.Dynamics.Commerce.RetailProxy.IEntityManager
    {
        
        /// <summary>
        /// UptailSearchLegacyPurchases method.
        /// </summary>
        /// <param name="customerAccountId">The customerAccountId.</param>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Uptail.CommerceRuntime.DataModels.LegacySalesTransaction.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.PagedResult<Uptail.CommerceRuntime.DataModels.LegacySalesTransaction>> UptailSearchLegacyPurchases(string customerAccountId, Microsoft.Dynamics.Commerce.Runtime.DataModel.QueryResultSettings queryResultSettings = null);
    
    }
    
    /// <summary>
    /// Interface for MagicBox Manager.
    /// </summary>
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public interface IMagicBoxManager : Microsoft.Dynamics.Commerce.RetailProxy.IEntityManager
    {
        
        /// <summary>
        /// GetMagicBoxDetails method.
        /// </summary>
        /// <param name="boxNumber">The boxNumber.</param>
        /// <returns>Uptail.CommerceRuntime.DataModels.MagicBox object.</returns>
        Task<Uptail.CommerceRuntime.DataModels.MagicBox> GetMagicBoxDetails(string boxNumber);
    
        /// <summary>
        /// updateMagicBox method.
        /// </summary>
        /// <param name="boxNumber">The boxNumber.</param>
        /// <returns>Uptail.CommerceRuntime.DataModels.MagicBox object.</returns>
        Task<Uptail.CommerceRuntime.DataModels.MagicBox> updateMagicBox(string boxNumber);
    
        /// <summary>
        /// GetAllMagicBoxes method.
        /// </summary>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Uptail.CommerceRuntime.DataModels.MagicBox.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.PagedResult<Uptail.CommerceRuntime.DataModels.MagicBox>> GetAllMagicBoxes(Microsoft.Dynamics.Commerce.Runtime.DataModel.QueryResultSettings queryResultSettings = null);
    
    }
    
    /// <summary>
    /// Interface for CustomerHistory Manager.
    /// </summary>
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public interface ICustomerHistoryManager : Microsoft.Dynamics.Commerce.RetailProxy.IEntityManager
    {
        
        /// <summary>
        /// GetCustomerHistory1 method.
        /// </summary>
        /// <param name="custometId">The custometId.</param>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Uptail.CommerceRuntime.DataModels.CustomerHistory.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.PagedResult<Uptail.CommerceRuntime.DataModels.CustomerHistory>> GetCustomerHistory1(string custometId, Microsoft.Dynamics.Commerce.Runtime.DataModel.QueryResultSettings queryResultSettings = null);
    
    }
    
    /// <summary>
    /// Interface for ItemBarCodes Manager.
    /// </summary>
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public interface IItemBarCodesManager : Microsoft.Dynamics.Commerce.RetailProxy.IEntityManager
    {
        
        /// <summary>
        /// GetItemBarCodes method.
        /// </summary>
        /// <param name="itemId">The itemId.</param>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Uptail.CommerceRuntime.DataModels.ItemBarCodes.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.PagedResult<Uptail.CommerceRuntime.DataModels.ItemBarCodes>> GetItemBarCodes(string itemId, Microsoft.Dynamics.Commerce.Runtime.DataModel.QueryResultSettings queryResultSettings = null);
    
    }
    
 }
