// <auto-generated />
  namespace Uptail.Commerce.RetailProxy.Extension
  {
  using System.CodeDom.Compiler;
  using System.IO;
  using System.Xml;

    /// <summary>
    /// Represents the EDM model.
    /// </summary>
    [GeneratedCodeAttribute("Uptail.Commerce.RetailProxy.Extension", "1.0")]
    public class EdmModel: Microsoft.Dynamics.Commerce.RetailProxy.IEdmModelExtension
    {
        private static string edmx = "<edmx:Edmx Version=\"4.0\" xmlns:edmx=\"http://docs.oasis-open.org/odata/ns/edmx\">\r\n" +
    "  <edmx:DataServices>\r\n    <Schema Namespace=\"Microsoft.Dynamics.Retail.RetailSe" +
    "rverLibrary\" xmlns=\"http://docs.oasis-open.org/odata/ns/edm\">\r\n      <Action Nam" +
    "e=\"GetMagicBoxDetails\" IsBound=\"true\">\r\n        <Parameter Name=\"bindingParamete" +
    "r\" Type=\"Uptail.CommerceRuntime.DataModels.MagicBox\" />\r\n        <ReturnType Typ" +
    "e=\"Uptail.CommerceRuntime.DataModels.MagicBox\" />\r\n      </Action>\r\n      <Actio" +
    "n Name=\"updateMagicBox\" IsBound=\"true\">\r\n        <Parameter Name=\"bindingParamet" +
    "er\" Type=\"Uptail.CommerceRuntime.DataModels.MagicBox\" />\r\n        <ReturnType Ty" +
    "pe=\"Uptail.CommerceRuntime.DataModels.MagicBox\" />\r\n      </Action>\r\n      <Acti" +
    "on Name=\"GetAllMagicBoxes\" IsBound=\"true\">\r\n        <Parameter Name=\"bindingPara" +
    "meter\" Type=\"Collection(Uptail.CommerceRuntime.DataModels.MagicBox)\" />\r\n       " +
    " <ReturnType Type=\"Collection(Uptail.CommerceRuntime.DataModels.MagicBox)\" />\r\n " +
    "     </Action>\r\n      <Action Name=\"UptailSearchLegacyPurchases\">\r\n        <Para" +
    "meter Name=\"customerAccountId\" Type=\"Edm.String\" />\r\n        <ReturnType Type=\"C" +
    "ollection(Uptail.CommerceRuntime.DataModels.LegacySalesTransaction)\" />\r\n      <" +
    "/Action>\r\n      <Action Name=\"GetCustomerHistory1\" IsBound=\"true\">\r\n        <Par" +
    "ameter Name=\"bindingParameter\" Type=\"Uptail.CommerceRuntime.DataModels.CustomerH" +
    "istory\" />\r\n        <ReturnType Type=\"Collection(Uptail.CommerceRuntime.DataMode" +
    "ls.CustomerHistory)\" />\r\n      </Action>\r\n      <Action Name=\"GetItemBarCodes\" I" +
    "sBound=\"true\">\r\n        <Parameter Name=\"bindingParameter\" Type=\"Collection(Upta" +
    "il.CommerceRuntime.DataModels.ItemBarCodes)\" />\r\n        <Parameter Name=\"itemId" +
    "\" Type=\"Edm.String\" />\r\n        <ReturnType Type=\"Collection(Uptail.CommerceRunt" +
    "ime.DataModels.ItemBarCodes)\" />\r\n      </Action>\r\n      <EntityContainer Name=\"" +
    "CommerceContext\">\r\n        <EntitySet Name=\"DeserveMagicBox\" EntityType=\"Uptail." +
    "CommerceRuntime.DataModels.MagicBox\" />\r\n        <EntitySet Name=\"CustomerHistor" +
    "y\" EntityType=\"Uptail.CommerceRuntime.DataModels.CustomerHistory\" />\r\n        <E" +
    "ntitySet Name=\"ItemBarCodes\" EntityType=\"Uptail.CommerceRuntime.DataModels.ItemB" +
    "arCodes\" />\r\n        <ActionImport Name=\"UptailSearchLegacyPurchases\" Action=\"Mi" +
    "crosoft.Dynamics.Retail.RetailServerLibrary.UptailSearchLegacyPurchases\" />\r\n   " +
    "   </EntityContainer>\r\n    </Schema>\r\n    <Schema Namespace=\"Uptail.CommerceRunt" +
    "ime.DataModels\" xmlns=\"http://docs.oasis-open.org/odata/ns/edm\">\r\n      <EntityT" +
    "ype Name=\"MagicBox\">\r\n        <Key>\r\n          <PropertyRef Name=\"BoxNumber\" />\r" +
    "\n        </Key>\r\n        <Property Name=\"BoxNumber\" Type=\"Edm.String\" Nullable=\"" +
    "false\" />\r\n        <Property Name=\"BoxName\" Type=\"Edm.String\" />\r\n        <Prope" +
    "rty Name=\"BoxPurchased\" Type=\"Edm.Boolean\" />\r\n      </EntityType>\r\n      <Compl" +
    "exType Name=\"LegacySalesTransaction\">\r\n        <Property Name=\"StoreId\" Type=\"Ed" +
    "m.String\" />\r\n        <Property Name=\"TransactionId\" Type=\"Edm.String\" />\r\n     " +
    "   <Property Name=\"SalesDateTime\" Type=\"Edm.DateTimeOffset\" />\r\n        <Propert" +
    "y Name=\"Description\" Type=\"Edm.String\" />\r\n        <Property Name=\"ItemNumber\" T" +
    "ype=\"Edm.String\" />\r\n        <Property Name=\"Quantity\" Type=\"Edm.Decimal\" />\r\n  " +
    "      <Property Name=\"Price\" Type=\"Edm.Decimal\" />\r\n        <Property Name=\"Amou" +
    "nt\" Type=\"Edm.Decimal\" />\r\n        <Property Name=\"Currency\" Type=\"Edm.String\" /" +
    ">\r\n      </ComplexType>\r\n      <EntityType Name=\"CustomerHistory\">\r\n        <Key" +
    ">\r\n          <PropertyRef Name=\"CustometId\" />\r\n        </Key>\r\n        <Propert" +
    "y Name=\"CustometId\" Type=\"Edm.String\" Nullable=\"false\" />\r\n        <Property Nam" +
    "e=\"StoreId\" Type=\"Edm.String\" />\r\n        <Property Name=\"TransactionId\" Type=\"E" +
    "dm.String\" />\r\n        <Property Name=\"SalesDateTime\" Type=\"Edm.DateTimeOffset\" " +
    "/>\r\n        <Property Name=\"Description\" Type=\"Edm.String\" />\r\n        <Property" +
    " Name=\"ItemNumber\" Type=\"Edm.String\" />\r\n        <Property Name=\"Quantity\" Type=" +
    "\"Edm.Decimal\" />\r\n        <Property Name=\"Price\" Type=\"Edm.Decimal\" />\r\n        " +
    "<Property Name=\"Amount\" Type=\"Edm.Decimal\" />\r\n        <Property Name=\"Currency\"" +
    " Type=\"Edm.String\" />\r\n      </EntityType>\r\n      <EntityType Name=\"ItemBarCodes" +
    "\">\r\n        <Key>\r\n          <PropertyRef Name=\"Barcode\" />\r\n        </Key>\r\n   " +
    "     <Property Name=\"Barcode\" Type=\"Edm.String\" Nullable=\"false\" />\r\n        <Pr" +
    "operty Name=\"ItemId\" Type=\"Edm.String\" />\r\n        <Property Name=\"RetailVariant" +
    "Id\" Type=\"Edm.String\" />\r\n        <Property Name=\"ExtensionProperties\" Type=\"Col" +
    "lection(Microsoft.Dynamics.Commerce.Runtime.DataModel.CommerceProperty)\" />\r\n   " +
    "   </EntityType>\r\n    </Schema>\r\n  </edmx:DataServices>\r\n</edmx:Edmx>";
        private static string apiVersion = "7.3";
        private static System.Collections.Generic.Dictionary<System.Type, string> proxyTypeToRuntimeTypeNameMap = new System.Collections.Generic.Dictionary<System.Type, string>()
        {
        
            { typeof(Uptail.Commerce.RetailProxy.Extension.MagicBox), "Uptail.CommerceRuntime.DataModels.MagicBox" },
            { typeof(Uptail.Commerce.RetailProxy.Extension.CustomerHistory), "Uptail.CommerceRuntime.DataModels.CustomerHistory" },
            { typeof(Uptail.Commerce.RetailProxy.Extension.ItemBarCodes), "Uptail.CommerceRuntime.DataModels.ItemBarCodes" },
            { typeof(Uptail.Commerce.RetailProxy.Extension.LegacySalesTransaction), "Uptail.CommerceRuntime.DataModels.LegacySalesTransaction" }
        };
        private static System.Collections.Generic.Dictionary<string, System.Type> runtimeTypeNameToProxyTypeMap = new System.Collections.Generic.Dictionary<string, System.Type>()
        {
        
            { "Uptail.CommerceRuntime.DataModels.MagicBox", typeof(Uptail.Commerce.RetailProxy.Extension.MagicBox) },
            { "Uptail.CommerceRuntime.DataModels.CustomerHistory", typeof(Uptail.Commerce.RetailProxy.Extension.CustomerHistory) },
            { "Uptail.CommerceRuntime.DataModels.ItemBarCodes", typeof(Uptail.Commerce.RetailProxy.Extension.ItemBarCodes) },
            { "Uptail.CommerceRuntime.DataModels.LegacySalesTransaction", typeof(Uptail.Commerce.RetailProxy.Extension.LegacySalesTransaction) }
        };
        
        /// <summary>
        /// Gets the EDMX string.
        /// </summary>
        public string Edmx
        {
            get
            {
                return edmx;
            }
        }

        /// <summary>
        /// Gets the matched Retail Server API version.
        /// </summary>
        public string ApiVersion
        {
            get
            {
                return apiVersion;
            }
        }
        
        /// <summary>
        /// Gets the map from retail proxy type to commerce runtime type names.
        /// </summary>
        public System.Collections.Generic.Dictionary<System.Type, string> ProxyTypeToRuntimeTypeNameMap
        {
            get { return proxyTypeToRuntimeTypeNameMap; }
        }

        /// <summary>
        /// Gets the map from commerce runtime type names to retail proxy type.
        /// </summary>
        public System.Collections.Generic.Dictionary<string, System.Type> RuntimeTypeNameToProxyTypeMap
        {
            get { return runtimeTypeNameToProxyTypeMap; }
        }
    }
}
